modLoader="javafml"
loaderVersion="[34,)"
license="GPLv3"
issueTrackerURL="https://github.com/MrCrayfish/MrCrayfishFurnitureMod/issues"

[[mods]]
modId="morecfm"
version="1.1.1"
displayName="MrCrayfish's More Furniture Mod"
updateJSONURL="https://raw.githubusercontent.com/MrCrayfish/ModUpdates/master/morecfm/update.json"
displayURL="https://mrcrayfish.com/mods?id=morecfm"
logoFile="morefurniture.png"
credits="The people who helped me when I first started creating mods. I wouldn't be here without them!"
authors="MrCrayfish"
description="MrCrayfish's More Furniture Mod is addon to the base Furniture Mod that adds support for wood variants from other mods"
itemIcon="cfm:stripped_crimson_chair"
configBackground="minecraft:textures/block/stripped_crimson_stem.png"

[[dependencies.morecfm]]
    modId="forge"
    mandatory=true
    versionRange="[34.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.morecfm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.morecfm]]
    modId="cfm"
    mandatory=true
    versionRange="[7.0.0-pre20,)"
    ordering="AFTER"
    side="BOTH"