modLoader="javafml"
loaderVersion="[36,)"
license="GPLv3"
issueTrackerURL="https://github.com/MrCrayfish/MrCrayfishMoreFurnitureMod/issues"

[[mods]]
modId="morecfm"
version="1.3.1"
displayName="MrCrayfish's More Furniture Mod"
updateJSONURL="https://mrcrayfish.com/modupdatejson?id=morecfm"
displayURL="https://mrcrayfish.com/mods?id=morecfm"
logoFile="morefurniture.png"
credits="The people who helped me when I first started creating mods. I wouldn't be here without them!"
authors="MrCrayfish"
description="MrCrayfish's More Furniture Mod is addon to the base Furniture Mod that adds support for wood variants from other mods"

[[dependencies.morecfm]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.morecfm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.morecfm]]
    modId="cfm"
    mandatory=true
    versionRange="[7.0.0-pre22,)"
    ordering="AFTER"
    side="BOTH"

[modproperties.morecfm]
    catalogueItemIcon="cfm:stripped_crimson_chair"
    configuredBackground="minecraft:textures/block/stripped_crimson_stem.png"